In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
x=data.drop(['Outcome'],axis=1)
y=data['Outcome']
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

Using KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(x_train,y_train)
predictions=knn.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
ac=accuracy_score(y_test,predictions)
cm=confusion_matrix(y_test,predictions)

In [ ]:
print(cm)

[[77 23]
 [24 30]]


In [ ]:
ac

0.6948051948051948

Using Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic_regression=LogisticRegression()

In [ ]:
logistic_regression.fit(x_train,y_train)
predictions=logistic_regression.predict(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
ac=accuracy_score(y_test,predictions)
cm=confusion_matrix(y_test,predictions)

In [ ]:
print(cm)

[[88 12]
 [26 28]]


In [ ]:
ac

0.7532467532467533

Using Decision tree & Random Forest

In [ ]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()

In [ ]:
tree.fit(x_train,y_train)
predictions=tree.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
ac=accuracy_score(y_test,predictions)
cm=confusion_matrix(y_test,predictions)

In [ ]:
print(cm)

[[79 21]
 [28 26]]


In [ ]:
ac

0.6818181818181818

Using Random forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier()

In [ ]:
forest.fit(x_train,y_train)
predictions=forest.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
ac=accuracy_score(y_test,predictions)
cm=confusion_matrix(y_test,predictions)

In [ ]:
print(cm)

[[84 16]
 [27 27]]


In [ ]:
ac

0.7207792207792207

Using Support Vector Machine

In [ ]:
from sklearn.svm import SVC
svm=SVC()

In [ ]:
svm.fit(x_train,y_train)
predictions=svm.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
ac=accuracy_score(y_test,predictions)
cm=confusion_matrix(y_test,predictions)

In [ ]:
print(cm)

[[88 12]
 [29 25]]


In [ ]:
ac

0.7337662337662337

Using Naive Baye's Method

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()

In [ ]:
nb.fit(x_train,y_train)

GaussianNB()

In [ ]:
predictions=nb.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
ac=accuracy_score(y_test,predictions)
cm=confusion_matrix(y_test,predictions)

In [ ]:
print(cm)

[[82 18]
 [25 29]]


In [ ]:
ac

0.7207792207792207